Repository spyder-ide/website-spyder, pull requests merged in 2018-04, with the labels that each got.

#75 PR: Make banner higher res, align, and add more compelling screenshot
  assets/static/images/readme_banner.png
Labels: type:enhancement

#80 PR: Fix various minor textual issues related to the name and authors
  .gitignore
  AUTHORS
  LICENSE
  NOTICES
  README.md
  content/docs/contents.lr
  spyder_website.lektorproject
Labels: type:bug

#81 PR: Crop main banner for better viewing on smaller/wider screens
  assets/static/images/readme_banner.png
Labels: type:bug

#84 PR: Fix details in blog style
  assets/static/css/styles.css
Labels: type:bug

#86 PR: Final revision of banner to fix margins, increase size and improve displayed content
  assets/static/images/readme_banner.png
Labels: type:bug

#87 PR: Fix low resolution of banner image and improve size/margins further
  assets/static/images/readme_banner.png
Labels: type:bug

#92 PR: Add common content (links, badges and banner) to Readme and minor formatting fixes
  README.md
  assets/static/images/spyder_readme_banner.png
  assets/static/images/spyder_website_banner.png
  spyder_website.lektorproject
Labels: status:Ready to Review, type:task

#100 PR: Update red color in banners to 255, 33, 33 and harmonize logo thickness
  assets/static/images/spyder_readme_banner.png
  assets/static/images/spyder_website_banner.png
Labels: type:enhancement

#101 PR: Copyedit front page text for correctness, compelling tone and consistency
  content/contents.lr
Labels: type:enhancement

#104 PR: Minor tweaks to keep consistency, optimize breaks and refine wording
  content/contents.lr
Labels: type:bug

#107 PR: Remove the old orphan docs from the website content tree
  content/docs/console/console.png
  content/docs/console/contents.lr
  content/docs/contents.lr
  content/docs/debugging/contents.lr
  content/docs/editor/contents.lr
  content/docs/editor/editor1.png
  content/docs/editor/editor2.png
  content/docs/editor/editor3.png
  content/docs/explorer/contents.lr
  content/docs/explorer/explorer.png
  content/docs/explorer/explorer_menu1.png
  content/docs/explorer/explorer_menu2.png
  content/docs/findinfiles/contents.lr
  content/docs/findinfiles/findinfiles.png
  content/docs/help/contents.lr
  content/docs/help/help_plain.png
  content/docs/help/help_rich.png
  content/docs/help/help_source.png
  content/docs/historylog/contents.lr
  content/docs/historylog/historylog.png
  content/docs/installation/contents.lr
  content/docs/internalconsole/contents.lr
  content/docs/internalconsole/internalconsole.png
  content/docs/ipythonconsole/contents.lr
  content/docs/ipythonconsole/ipythonconsole.png
  content/docs/ipythonconsole/ipythonconsolemenu.png
  content/docs/ipythonconsole/ipythonkernelconnect.png
  content/docs/onlinehelp/contents.lr
  content/docs/onlinehelp/onlinehelp.png
  content/docs/options/contents.lr
  content/docs/overview/contents.lr
  content/docs/projectexplorer/contents.lr
  content/docs/projectexplorer/git_install_dialog.png
  content/docs/projectexplorer/projectexplorer.png
  content/docs/projectexplorer/projectexplorer2.png
  content/docs/pylint/contents.lr
  content/docs/pylint/pylint.png
  content/docs/variableexplorer/arrayeditor.png
  content/docs/variableexplorer/contents.lr
  content/docs/variableexplorer/dicteditor.png
  content/docs/variableexplorer/listeditor.png
  content/docs/variableexplorer/texteditor.png
  content/docs/variableexplorer/variableexplorer-imshow.png
  content/docs/variableexplorer/variableexplorer-plot.png
  content/docs/variableexplorer/variableexplorer1.png
  content/docs/variableexplorer/variableexplorer2.png
Labels: status:Ready to Review, type:techdebt
